name: ci
on:
  push:
    branches:
      - master
  pull_request: {} # Validate all PRs

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ghc: ['9.6']
        include:
        - os: macOS-latest
          ghc: 'latest'
    steps:
    - uses: actions/checkout@v3
    - name: Install libncurses5 and libtinfo
      if: runner.os == 'Linux' && (matrix.ghc == '8.0' || matrix.ghc == '8.2')
      run: |
        sudo apt-get install libncurses5 libtinfo5
    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Update cabal package database
      run: cabal update
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Test
      run: |
        cabal sdist -z -o .
        cabal get base64-bytestring-kadena-*.tar.gz
        cd base64-bytestring-kadena-*/
        cabal build base64-bytestring-kadena:tests --enable-tests --enable-benchmarks
        cabal test --enable-tests --enable-benchmarks --test-show-details=direct all
